global:
    scrape_interval: 15s
    external_labels:
      monitor: 'hygge-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'hygge'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.124.9:9000']
        labels:
          group: 'hyggecloud'
